const ActionType = {
    GET_POKEMON_TYPES: 'GET_POKEMON_TYPES',
    GET_POKEMON_OWNED: 'GET_POKEMON_OWNED',
    GET_POKEMON_OWNED_COUNT: 'GET_POKEMON_OWNED_COUNT',
    GET_POKEMON_SPECIES: 'GET_POKEMON_SPECIES',
    GET_POKEMON: 'GET_POKEMON',
}

export default ActionType;